spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: project-asymmetric-keys
  datasource:
        url: jdbc:postgresql://${db_url}:${db_port}/${db_name}
        username: ${db_username}
        password: ${db_password}
        driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql:
        jdbc:
          time_zone: ${db_timezone}
    database: postgresql
    show-sql: true

app:
  security:
    jwt:
      expiration:
        access-token: 900000 # 15 minutes
        refresh-token: 604800000 # 7 days
    disposable-email:
      - 10minutemail
      - 20minutemail
      - 33mail
      - 5ymail
      - anonbox
      - guerrillamail
      - maildrop
      - mailinator
      - mailnesia
      - moakt
      - my10minutemail
      - temp-mail
      - tempmail
      - throwawaymail
      - trashmail
      - truemail
      - yopmail